[project]
name = "sole-agent"
version = "0.0.0"
description = "Sole-Agent (Learningpath - Introductory)"
readme = "README.md"
requires-python = ">=3.11, <3.13"
dependencies = [
    "core_lib",
]

[tool.uv.sources]
core = { path = "../core-lib/dist/core_lib-0.0.0-py3-none-any.whl" }

