[project]
name = "sole-agent"
version = "0.0.0"
description = "Sole-Agent (Learningpath - Introductory)"
readme = "README.md"
requires-python = ">=3.11, <3.13"
dependencies = [
    "corelibs",
]

[tool.uv.sources]
core = { path = "../corelibs/dist/corelibs-0.0.0-py3-none-any.whl" }

